(function(){(function(b){var f=function(a){for(var a=a.split("."),d=this,c=a[0]==="window"?1:0;c<a.length;c++)d=d[a[c]]||(d[a[c]]={});return d},h=f(b);if(!(h.load&&typeof h.load==="function")){var k=function(){return!0},i={},j={},q=function(){for(var a in j)j.hasOwnProperty(a)&&j[a]&&!j[a].cancelled&&j[a].load()},l=function(a,d){for(var c=i[a],g=c?c.length:0;g--;)if(c[g].name===d)return c[g];throw"unknown:[$1]".replace("$1",a+":"+d);},n=function(a,d){var c;if(!d||d==="auto")a:{for(var g=(c=i[a])?c.length:0,e=
0;e<g;e++)if(c[e].readyState==="complete"||c[e].readyState==="loading"){c=c[e];break a}for(e=0;e<g;e++)if(c[e].detector()){c=c[e];break a}c=null}else c=d==="none"?null:l(a,d);return c},o=function(a){var a=a||k,d={},c,g,e;for(g in i)if(i.hasOwnProperty(g)){c=[];for(e=0;e<i[g].length;e++)a(i[g][e])&&c.push(i[g][e].name);c.length>0&&(d[g]=c)}return d},r=0,m=function(a,d,c,g,e,b,f){this.featureName=a;this.name=d;this.loadPath=c;this.detector=g||k;this.dependencies=e;this.charset=b||"utf-8";this.loadCallback=
f;this.readyState="uninitialized"};m.prototype={onWrite:function(a){this.readyState="loading";a&&q()},onLoad:function(a){a&&this.onWrite(a);this.readyState="complete";q()},canLoad:function(a,d){for(var c=this.dependencies,g=c?c.length:0,e;g--;){if(a[c[g]]==="none")throw"conflict:[$1]->[$2]".replace("$1",this.featureName).replace("$2",c[g]);e=n(c[g],a[c[g]]||"auto");if(e.readyState==="uninitialized"||!d&&e.readyState==="loading")return!1}return!0},onLoadCallback:function(a){this.loadCallback&&this.loadCallback();
(a=a.getElementById("_onLoad"+this.featureName+"_"+this.name))&&a.parentNode&&a.parentNode.removeChild(a)},writeSync:function(a,d){this.readyState="loading";a.write('<script type="text/javascript" charset="$ENC$" src="$SRC$"><\/script>'.replace("$SRC$",this.loadPath).replace("$ENC$",this.charset));this.loadCallback&&a.write('<script id="$ID$" type="text/javascript" charset="utf-8">$CONTENT$<\/script>'.replace("$ID$","_onLoad"+this.featureName+"_"+this.name).replace("$CONTENT$",b+".get('"+this.featureName+
"','"+this.name+"').onLoadCallback("+b+".loaders["+d+"].doc)"));this.onLoad(!0)},writeAsync:function(a,d,c){this.readyState="loading";var g=this,e=a.createElement("script");d&&(e.async=!1);e.type="text/javascript";e.charset=this.charset;e.onload=e.onreadystatechange=function(){var c=e.readyState;if(!c||/^(?:loaded|complete)$/i.test(c))e.onload=e.onreadystatechange=null,g.onLoadCallback&&g.onLoadCallback(a),g.onLoad(d)};e.onerror=function(a){c(a)};e.src=this.loadPath;a.getElementsByTagName("head")[0].appendChild(e);
this.onWrite(d)}};m.prototype.featureName=null;m.prototype.onLoadCallback=m.prototype.onLoadCallback;m.prototype.readyState=null;var p=function(a,d,c,g,e){g=g||document;this.requested=a;this.onSuccess=d||k;this.onError=c||k;this.doc=g;this.writeSync=this.inHead=e||g.readyState!="complete";this.id=r++;j[this.id]=this};p.prototype={onFinished:function(a){delete j[this.id];if(a)this.onError(a);else this.onSuccess();(a=this.doc.getElementById("_onSuccess"+this.id))&&a.parentNode&&a.parentNode.removeChild(a)},
load:function(){var a=this.requested,d,c,g=!0,e=this;try{for(c in a)i[c]&&(d=n(c,a[c]))&&this.loadSingle(d,a,this.inHead,this.writeSync,function(a){e.onFinished(a)})&&(g=!1);g&&this.onDone()}catch(b){this.onFinished(b),this.onFinished=k}},onDone:function(){if(!this.done){var a=this;this.inHead?document.write('<script id="$ID$" type="text/javascript" charset="utf-8">$CONTENT$<\/script>'.replace("$ID$","_onSuccess"+a.id).replace("$CONTENT$",b+".loaders["+a.id+"].onFinished();")):window.setTimeout(function(){a.onFinished()},
1);this.done=!0}},loadSingle:function(a,d,c,g,e){if(a.readyState==="complete")return!1;else if(a.readyState==="loading")return!0;var b,f;if(a.canLoad(d,g))c?a.writeSync(this.doc,this.id):a.writeAsync(this.doc,g,e);else{a=a.dependencies;for(b=a.length;b--;)f=n(a[b],d[a[b]]||"auto"),this.loadSingle(f,d,c,g,e)}return!0}};p.prototype.onFinished=p.prototype.onFinished;p.prototype.id=null;p.prototype.doc=null;h.loaders=j;h.features=i;h._detectors={};h.get=n;h.add=function(a,d,c,b,e,f,p){(i[a]||(i[a]=[])).push(new m(a,
d,c,b,e,p,f))};h.isLoaded=function(a,d){return l(a,d).readyState==="complete"};h.load=function(a,d,c,b,e){(new p(a,d,c,b,e)).load()};h.getFeatureMap=function(){return o(function(a){return a.featureName!="base"})};h.getLoadedMap=function(){return o(function(a){return a.featureName!="base"&&a.readyState==="complete"})};f("nokia.maps").Features=h}})("nokia.Features");nokia.maps.Features._detectors["ui-ovi_web"]=function(){return!0};
nokia.maps.Features._detectors["ui-nokia_generic"]=function(){var b=navigator.userAgent.toLowerCase(),f=function(){var b=document.createElement("canvas");if(!b||!b.getContext)return!1;return typeof b.getContext("2d").fillText==="function"}(),h=document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure","1.1"),k=b.match(/msie/)&&!window.opera&&!f,b=b.match(/msie\s7/);return f||h||k&&!b};nokia.maps.Features._detectors["search-nokia"]=function(){return!0};
nokia.maps.Features._detectors["routing-nokia"]=function(){return!0};nokia.maps.Features._detectors["positioning-w3c"]=function(){var b=!1;try{b=!(!navigator||!(navigator.geolocation&&typeof navigator.geolocation.getCurrentPosition==="function"))}catch(f){}return b};nokia.maps.Features._detectors["behavior-touch"]=function(){return!0};nokia.maps.Features._detectors["behavior-all"]=function(){return!0};nokia.maps.Features._detectors["map-js-p2d-dom"]=function(){return!0};
nokia.maps.Features._detectors["map-js-p2d-canvas"]=function(){var b=document.createElement("canvas");return!(!b.getContext||!b.getContext("2d"))};nokia.maps.Features._detectors["gfx-vml"]=function(){return!document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure","1.1")};nokia.maps.Features._detectors["gfx-svg"]=function(){return document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure","1.1")};
nokia.maps.Features._detectors["gfx-canvas"]=function(){var b=document.createElement("canvas");if(!b||!b.getContext)return!1;return typeof b.getContext("2d").fillText==="function"};this.nokia.maps=this.nokia.maps||{};this.nokia.maps.build="nokiamapsapi-2.1.1-Bianca-20120207-w6-r13204";
(function(b){var f=b.config||{};f.packages=f.packages||{search:[{name:"nokia"}],routing:[{name:"nokia"}],positioning:[{name:"w3c"}],map:[{name:"js-p2d-canvas",dependencies:["gfx"]},{name:"js-p2d-dom",dependencies:["gfx"]}],behavior:[{name:"all"},{name:"touch"}],gfx:[{name:"canvas"},{name:"svg"},{name:"vml"}],ui:[{name:"nokia_generic",dependencies:["gfx"]},{name:"ovi_web"}],language:[{name:"zh-CN"},{name:"en-GB"}]};f.addons=f.addons||{kml:[{name:"kml"}],heatmap:[{name:"heatmap",dependencies:["map"]}]};
f["routing.baseUrl"]="http://pr.pek.mos.svc.ovi.com/";f["routing.map_minor_version"]=2;f["routing.map_feature_version"]=41;f["routing.map_build_version"]=11;f["search.baseUrl"]="http://nose.svc.maps.nokia.com.cn/";f["search.reversegeocode.baseUrl"]="http://pr.geo.maps.svc.ovi.com.cn/";f.assetsPath=f.assetsPath||"assets/ovi/mapsapi";f.tileProviders=f.tileProviders||"nokia.maps.map.js.nokiaChinaTileProviders";f.copyright=f.copyright||"nokia.maps.map._Copyright";f["language.warnOnMissingTranslation"]=
f["language.warnOnMissingTranslation"]||!1;f.includePlaces=!0;b.config=f})(this.nokia.maps);nokia.maps.config=this.nokia.maps.config;
(function(b){var f,h,k={};h=function(b){if(k[b])return k[b];for(var a=b.replace(".","\\."),d=document.getElementsByTagName("script"),c=d.length,a=RegExp("^(.*\\/"+a+".*|"+a+".*)");c--;)if(a.test(d[c].src))return k[b]=d[c].src,k[b];throw"InternalError: could not locate "+b+" in the environment.";};var i=function(b){for(var a=/([\\?&]([^=]+)=([^&#]+))/g,d,c={};d=a.exec(b);)c[d[2]]=d[3];return c};if(!b.assetsPath)throw"Internal Error: no asset path has been specified";f=b.loadPath||function(b){b=b.split("/").slice(0,
-1);return b.join("/")+(b.length>0?"/":"")}(h("jsl.js"));h=b.params||i(h("jsl.js"));var j,q,l,n,o=nokia.maps.Features,r=this,m=function(b){n=b.dependencies||[];n.push("base");q=j+"-"+b.name;o.add(j,b.name,f+q+".js",o._detectors[q],n)};for(j in b.packages){i=b.packages[j];for(l=0;l<i.length;l++)m(i[l]);j!="language"&&!h[j]&&(h[j]="auto")}if(b.addons)for(j in b.addons){i=b.addons[j];for(l=0;l<i.length;l++)m(i[l])}o.add("base","noovi",f+"base_noovi.js",function(){return r.ovi&&r.ovi.win});o.add("base",
"withovi",f+"base.js",function(){return!r.ovi||!r.ovi.win});b.params=h;b.baseUrl=f;h.blank||o.load(h,null,function(b){throw b;},null,!0)})(this.nokia.maps.config);})();
